### ISSUE TITLE
Hello, this soft only display "Wetness" images?

### ISSUE THREAD

**Issue by Yinshao-lzu** [eMapR/TimeSync-Legacy#2]
Hello, Could this soft display other composite image?
![QQ截图20210330102701](https://user-images.githubusercontent.com/56902640/112924319-7b73fc80-9142-11eb-91e3-2757077c6f66.png)

**Comment by jdbcode** [comment]
The image chips and chart point color can only be represented as tasseled cap brightness, greenness, wetness = red, green, blue.

**Comment by Yinshao-lzu** [comment]
Thanks！
